[scylla_nodes]
scylla1 ansible_host=16.147.230.26 ansible_user=ubuntu private_ip=172.31.31.46
scylla2 ansible_host=16.147.222.180 ansible_user=ubuntu private_ip=172.31.27.44
scylla3 ansible_host=18.236.162.135 ansible_user=ubuntu private_ip=172.31.27.60

[monitoring_node]
monitoring ansible_host=34.213.177.187 ansible_user=ubuntu private_ip=172.31.27.96

[client_nodes]
client ansible_host=16.145.54.108 ansible_user=ubuntu private_ip=172.31.18.147
